import { Job } from "../models/job.model.js";

export const seedJobs = async () => {
  await Job.deleteMany();

  await Job.insertMany([
    {
      title: "React Developer",
      company: "Google",
      location: "Remote",
      salary: 120000,
      category: "frontend",
      description: "Build UI applications",
    },
    {
      title: "Node.js Backend Engineer",
      company: "Amazon",
      location: "Bangalore",
      salary: 150000,
      category: "backend",
      description: "Work on APIs",
    },
    {
      title: "Fullstack Developer",
      company: "Microsoft",
      location: "Hyderabad",
      salary: 140000,
      category: "fullstack",
      description: "Frontend + Backend",
    },
    {
      title: "Frontend Engineer",
      company: "Meta",
      location: "Remote",
      salary: 130000,
      category: "frontend",
      description: "Build scalable UI systems",
    },
    {
      title: "Backend Developer",
      company: "Netflix",
      location: "Chennai",
      salary: 145000,
      category: "backend",
      description: "Microservices & APIs",
    },
    {
      title: "Software Engineer",
      company: "Adobe",
      location: "Noida",
      salary: 125000,
      category: "fullstack",
      description: "Work across stack",
    },
    {
      title: "UI Developer",
      company: "Flipkart",
      location: "Bangalore",
      salary: 110000,
      category: "frontend",
      description: "Develop responsive UI",
    },
    {
      title: "API Developer",
      company: "Paytm",
      location: "Delhi",
      salary: 135000,
      category: "backend",
      description: "Build REST APIs",
    },
    {
      title: "Fullstack Engineer",
      company: "Swiggy",
      location: "Remote",
      salary: 150000,
      category: "fullstack",
      description: "End-to-end development",
    },
    {
      title: "React UI Engineer",
      company: "Zomato",
      location: "Gurgaon",
      salary: 120000,
      category: "frontend",
      description: "Build UI components",
    },
    {
      title: "Node.js Developer",
      company: "Razorpay",
      location: "Bangalore",
      salary: 140000,
      category: "backend",
      description: "Payment APIs",
    },
    {
      title: "Software Developer",
      company: "TCS",
      location: "Hyderabad",
      salary: 90000,
      category: "fullstack",
      description: "Enterprise apps",
    },
    {
      title: "Frontend Developer",
      company: "Infosys",
      location: "Pune",
      salary: 95000,
      category: "frontend",
      description: "UI for enterprise tools",
    },
    {
      title: "Backend Engineer",
      company: "Wipro",
      location: "Chennai",
      salary: 100000,
      category: "backend",
      description: "Server-side logic",
    },
    {
      title: "MERN Stack Developer",
      company: "StartupX",
      location: "Remote",
      salary: 105000,
      category: "fullstack",
      description: "MERN applications",
    },
  ]);

  console.log("🌱 Seed data inserted");
};
